#!/usr/bin/python

"""Reads an OPML file, gets all feeds in it and writes Blosxom entries
corresponding to the items in the feeds."""

# $Id$

import os, sys, getopt

from Plagg import Plagg

PATH = '/home/bb/bblog/news'
OPML = os.path.join(PATH, 'news.opml')

def usage(rc):
    print "Usage: plagg [-nhVv] [opmlfile [newsdir [nickname ...]]]"
    sys.exit(rc)

news = verbose = 0
try:
    opts, args = getopt.getopt(sys.argv[1:], 'nhVv')
except getopt.GetoptError:
    print e
    usage(3)
for o, v in opts:
    if o == '-n':
	news = 1
    if o == '-h':
	usage(0)
    elif o == '-V':
	print "$Id$"
	sys.exit(0)
    elif o == '-v':
	verbose += 1
argc = len(args)
if argc == 0:
    plagg = Plagg.Plagg(OPML, PATH)
elif argc == 1:
    plagg = Plagg.Plagg(args[0], PATH)
elif argc == 2:
    plagg = Plagg.Plagg(args[0], args[1])
elif argc >= 3:
    plagg = Plagg.Plagg(args[0], args[1], args[2:])
else:
    usage(3)

plagg.setLogging(verbose)
plagg.startOPML()
if news:
    plagg.newEntries()

sys.exit(plagg.errors and 1 or 0)
